### ISSUE TITLE
Help using rewardable

### ISSUE THREAD

**Issue by simonfranz** [DraperStudio/Laravel-Rewardable#3]
Hi there,
maybe I'm misssing something, but I don't get the plugin to work.

My model looks like described in the index

```
use DraperStudio\Rewardable\Traits\Rewardable as RewardableTrait;
use Illuminate\Auth\Authenticatable;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Illuminate\Database\Eloquent\Model;

class User extends Model implements AuthenticatableContract, CanResetPasswordContract {

	use Authenticatable, CanResetPassword, RewardableTrait;
```

I've also published the migraitons and have executed them.
In a view after the login I've tried to print all the gained credits (none at this time)
`{{dump(Auth::user()->getCredit())}}`
The same happens if I'm getting a direct model object with
`{{dump(\App\Models\User::find(1)->getCredit())}}`

Saldy I only get this Exception:
```
Next ErrorException: Call to undefined method Illuminate\Database\Query\Builder::getCredit() (View: /home/s/www/test/resources/views/layouts/login.blade.php) (View: /home/s/www/test/resources/views/layouts/login.blade.php) (View: /home/s/www/test/resources/views/layouts/login.blade.php) (View: /home/s/www/test/resources/views/layouts/login.blade.php) in /home/s/www/test/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2093
Stack trace:
#0 /home/s/www/test/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
#1 /home/s/www/test/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(58): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/simon/www...', Array)
#2 /home/s/www/test/vendor/laravel/framework/src/Illuminate/View/View.php(142): Illuminate\View\Engines\CompilerEngine->get('/home/simon/www...', Array)
#3 /home/s/www/test/vendor/laravel/framework/src/Illuminate/View/View.php(113): Illuminate\View\View->getContents()
#4 /home/s/www/test/vendor/laravel/framework/src/Illuminate/View/View.php(82): Illuminate\View\View->renderContents()
#5 /home/s/www/test/vendor/laravel/framework/src/Illuminate/Http/Response.php(51): Illuminate\View\View->render()
#6 /home/s/www/test/vendor/symfony/http-foundation/Response.php(198): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /home/s/www/test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1229): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 /home/s/www/test/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#9 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 /home/s/www/test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#11 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#12 /home/s/www/test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#13 /home/s/www/test/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#14 /home/s/www/test/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(67): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\HomeController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'index')
#15 /home/s/www/test/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'index')
#16 /home/s/www/test/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#17 /home/s/www/test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#18 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /home/s/www/test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#20 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 /home/s/www/test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#22 /home/s/www/test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#23 /home/s/www/test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(673): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#24 /home/s/www/test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#25 /home/s/www/test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#26 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#27 /home/s/www/test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#28 /home/s/www/test/app/Http/Middleware/SetLanguage.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 [internal function]: App\Http\Middleware\SetLanguage->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /home/s/www/test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#31 /home/s/www/test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /home/s/www/test/app/Http/Middleware/VerifyCsrfToken.php(17): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 [internal function]: App\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /home/s/www/test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#35 /home/s/www/test/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /home/s/www/test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#38 /home/s/www/test/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /home/s/www/test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#41 /home/s/www/test/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /home/s/www/test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#44 /home/s/www/test/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /home/s/www/test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#47 /home/s/www/test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /home/s/www/test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#50 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 /home/s/www/test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#52 /home/s/www/test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#53 /home/s/www/test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#54 /home/s/www/test/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#55 {main}
```

Did I miss something, could you maybe help me to get this working? It seems i might missed something integrating the package, but I don't get what's missing.

Regards

**Comment by DraperStudio** [comment]
Are you using Laravel 5.1 or 5.2?

**Comment by simonfranz** [comment]
Currently I'm using Laravel 5.1

**Comment by DraperStudio** [comment]
Have it integrated in some 5.1 projects and no issues so I will need to take a look at this during the weekend.

**Comment by simonfranz** [comment]
Thanks, I would appreciate it.
Please ask if you need any additional informations :-)

**Comment by DraperStudio** [comment]
I just tried the following in Laravel 5.1 and 5.2

```php
Route::get('/', function () {
    dd(\App\User::find(1)->getCredit());
});
```

```php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use DraperStudio\Rewardable\Traits\Rewardable as RewardableTrait;

class User extends Authenticatable
{
    use RewardableTrait;
}
```

Seeded some users and it just worked so I can't really reproduce your error.

**Comment by simonfranz** [comment]
Sorry, I've found the bug, it seemed that I have had multiple User models defined in differend namespaces. Therefore I've included the RewardableTrait in a wrong model. 
I'm very sorry.
Time to clean out some model-classes...

**Comment by DraperStudio** [comment]
You shouldn't have multiple user models in one project, rather use roles and permissions.

**Comment by simonfranz** [comment]
Yes I've copied the initial user from \App\ to my Models Folder \App\Models\ then i accidentally didn't deleted the User in \App\. Without noticing I have edited the wrong User-class.
Thanks
